### ISSUE TITLE
I have a patch.

### ISSUE THREAD

**Issue by kollokollo** [mmuman/gfalist#1]
I have a patch. How can I subit it to be merged with this repository?

**Comment by mmuman** [comment]
Hi, for a small patch you can probably assign them to a (properly named) ticket, after generating it with git add + git commit + git format-patch. The proper way however is to fork the repo and make a pull-request with your commits.
See the github help pages: https://help.github.com/

**Comment by kollokollo** [comment]
I'd like to do so, but I get an error:
remote: Permission to mmuman/gfalist.git denied to kollokollo.
fatal: unable to access 'https://github.com/mmuman/gfalist/': The requested URL returned error: 403

**Comment by mmuman** [comment]
Which command did you use that gives this error? git push will refuse you the permission to push to a repo you don't have rights to. That's why we fork, and they push to our own repo before making a pull-request form our own repo to the main repo.

**Comment by kollokollo** [comment]
OK, I see. I have cloned the repro to my disk and made the changes there. Ill try a fork...

**Comment by mmuman** [comment]
As I said, if the changes are small you can do
```
git add foo.c bar.h
git commit
git format-patch origin
```
and attach the patch to an issue ticket. Although I'm not sure github already allows patches as attachements... oh, you'd have to rename it to a .txt [it seems](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by mmuman** [comment]
Thanks!
